function data = preprocessVehicleData(rawData, cfg)
%PREPROCESSVEHICLEDATA Run the full preprocessing pipeline.

data = removeMissingSamples(rawData);
data = resampleVehicleData(data, cfg.targetSampleTime_s);

signalsToFilter = [ ...
    "steering_wheel_angle_deg", ...
    "yaw_rate_degps", ...
    "lateral_accel_mps2", ...
    "longitudinal_accel_mps2", ...
    "roll_rate_degps", ...
    "vertical_accel_mps2" ...
];

for i = 1:numel(signalsToFilter)
    col = signalsToFilter(i);
    data.(col) = lowPassFilterSignal(data.(col), cfg.lowPass.windowSamples);
end
end
